### ISSUE TITLE
License

### ISSUE THREAD

**Issue by berviantoleo** [MartinChavez/Javascript#3]
Hi, I don't see License on this repository, or in [https://github.com/MartinChavez/Javascript](https://github.com/MartinChavez/Javascript).

I suggest to have License in this repository. Good for tutorial have a license. You can add LICENSE file to your repository. LICENSE can fit to you is MIT License. If you want me to add the license, I happy to add that.

**Comment by MartinChavez** [comment]
Thanks @berviantoleo ! I have added a license.
